import { createClient } from '@supabase/supabase-js'

// export const supabase = createClient('https://ffxiscwkuramynmzymav.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeGlzY3drdXJhbXlubXp5bWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYyODE4MzIsImV4cCI6MjAyMTg1NzgzMn0.1ORv-s9lDA54FyhrlgW8S6iluES0uhybYx8BB5QuhSk')
export const supabase = createClient('https://ffxiscwkuramynmzymav.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmeGlzY3drdXJhbXlubXp5bWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDYyODE4MzIsImV4cCI6MjAyMTg1NzgzMn0.1ORv-s9lDA54FyhrlgW8S6iluES0uhybYx8BB5QuhSk')
